### ISSUE TITLE
Datasets in proper format

### ISSUE THREAD

**Issue by dtortorella** [dtortorella/bundle-svm#1]
Upload the datatasets (MONK1-3, ML-CUP) in a CSV format that can be read by Matlab.
The files must be in the directory named `data`, with lowercase names of the form `dataset-name.{train, test}.csv`.

**Comment by fferrante3** [comment]
Fixed in commit https://github.com/dtortorella/bundle-svm/commit/9392c2ce6d43aa3895f416e5cb58bdf7f1252ba5
